import type { KnowledgeAtom } from "@/domain/learning/types";
import { atom } from "./atom";

/** Core MSA grammar atoms for early A1. Load after common words. */
export const GRAMMAR_ATOMS: KnowledgeAtom[] = [
  atom({
    id: "grammar-al",
    kind: "GRAMMAR",
    canonicalArabic: "ال",
    vocalizedArabic: "ال",
    englishGloss: "definite article (al-)",
    prerequisiteIds: ["letter-alif", "letter-lam"],
    patternNote: "Prefixes to nouns; sun/moon letter assimilation later",
  }),
  atom({
    id: "grammar-sun-letters",
    kind: "GRAMMAR",
    canonicalArabic: "الـ + شمس",
    vocalizedArabic: "الشَّمْس",
    englishGloss: "sun letters assimilate lām of al-",
    prerequisiteIds: ["grammar-al", "word-shams"],
  }),
  atom({
    id: "grammar-moon-letters",
    kind: "GRAMMAR",
    canonicalArabic: "الـ + قمر",
    vocalizedArabic: "القَمَر",
    englishGloss: "moon letters keep lām of al- pronounced",
    prerequisiteIds: ["grammar-al", "word-qamar"],
  }),
  atom({
    id: "particle-fi",
    kind: "WORD",
    canonicalArabic: "في",
    vocalizedArabic: "فِي",
    englishGloss: "in; at",
    prerequisiteIds: ["letter-fa", "letter-ya"],
  }),
  atom({
    id: "particle-min",
    kind: "WORD",
    canonicalArabic: "من",
    vocalizedArabic: "مِنْ",
    englishGloss: "from; of",
    prerequisiteIds: ["letter-mim", "letter-nun"],
  }),
  atom({
    id: "particle-ila",
    kind: "WORD",
    canonicalArabic: "إلى",
    vocalizedArabic: "إِلَى",
    englishGloss: "to; toward",
    prerequisiteIds: ["letter-alif", "letter-lam"],
  }),
  atom({
    id: "particle-3ala",
    kind: "WORD",
    canonicalArabic: "على",
    vocalizedArabic: "عَلَى",
    englishGloss: "on; upon",
    prerequisiteIds: ["letter-ain", "letter-lam"],
  }),
  atom({
    id: "particle-ma3a",
    kind: "WORD",
    canonicalArabic: "مع",
    vocalizedArabic: "مَعَ",
    englishGloss: "with",
    prerequisiteIds: ["letter-mim", "letter-ain"],
  }),
  atom({
    id: "particle-wa",
    kind: "WORD",
    canonicalArabic: "و",
    vocalizedArabic: "وَ",
    englishGloss: "and",
    prerequisiteIds: ["letter-waw"],
  }),
  atom({
    id: "particle-aw",
    kind: "WORD",
    canonicalArabic: "أو",
    vocalizedArabic: "أَوْ",
    englishGloss: "or",
    prerequisiteIds: ["letter-alif-hamza", "letter-waw"],
  }),
  atom({
    id: "particle-lakin",
    kind: "WORD",
    canonicalArabic: "لكن",
    vocalizedArabic: "لٰكِنْ",
    englishGloss: "but",
    prerequisiteIds: ["letter-lam", "letter-kaf", "letter-nun"],
  }),
  atom({
    id: "particle-li",
    kind: "WORD",
    canonicalArabic: "لـ",
    vocalizedArabic: "لِ",
    englishGloss: "for; to (preposition)",
    prerequisiteIds: ["letter-lam"],
  }),
  atom({
    id: "particle-bi",
    kind: "WORD",
    canonicalArabic: "بـ",
    vocalizedArabic: "بِ",
    englishGloss: "with; by means of",
    prerequisiteIds: ["letter-ba"],
  }),
  atom({
    id: "grammar-huwa-hiya",
    kind: "GRAMMAR",
    canonicalArabic: "هو / هي",
    vocalizedArabic: "هُوَ / هِيَ",
    englishGloss: "he vs she (basic gender agreement cue)",
    prerequisiteIds: ["pronoun-huwa", "pronoun-hiya"],
  }),
  atom({
    id: "grammar-idafa-intro",
    kind: "GRAMMAR",
    canonicalArabic: "كتاب الطالب",
    vocalizedArabic: "كِتَابُ الطَّالِبِ",
    englishGloss: "possessive construct (iḍāfa) intro",
    prerequisiteIds: ["word-kitab", "word-talib", "grammar-al"],
    patternNote: "First noun loses tanwīn; second often definite",
  }),
  atom({
    id: "grammar-la-negation",
    kind: "GRAMMAR",
    canonicalArabic: "لا + مضارع",
    vocalizedArabic: "لَا أَفْهَمُ",
    englishGloss: "negating present with lā",
    prerequisiteIds: ["word-la", "verb-afham"],
  }),
  atom({
    id: "grammar-hal-question",
    kind: "GRAMMAR",
    canonicalArabic: "هل",
    vocalizedArabic: "هَلْ",
    englishGloss: "yes/no question particle",
    prerequisiteIds: ["letter-ha", "letter-lam", "word-naam"],
  }),
  atom({
    id: "grammar-ma-what",
    kind: "GRAMMAR",
    canonicalArabic: "ما",
    vocalizedArabic: "مَا",
    englishGloss: "what?",
    prerequisiteIds: ["letter-mim", "letter-alif"],
  }),
  atom({
    id: "grammar-man-who",
    kind: "GRAMMAR",
    canonicalArabic: "من",
    vocalizedArabic: "مَنْ",
    englishGloss: "who?",
    prerequisiteIds: ["letter-mim", "letter-nun"],
  }),
  atom({
    id: "grammar-ayna-where",
    kind: "GRAMMAR",
    canonicalArabic: "أين",
    vocalizedArabic: "أَيْنَ",
    englishGloss: "where?",
    prerequisiteIds: ["letter-alif-hamza", "letter-ya", "letter-nun"],
  }),
  atom({
    id: "grammar-mata-when",
    kind: "GRAMMAR",
    canonicalArabic: "متى",
    vocalizedArabic: "مَتَى",
    englishGloss: "when?",
    prerequisiteIds: ["letter-mim", "letter-ta"],
  }),
  atom({
    id: "grammar-kam-how-many",
    kind: "GRAMMAR",
    canonicalArabic: "كم",
    vocalizedArabic: "كَمْ",
    englishGloss: "how many / how much?",
    prerequisiteIds: ["letter-kaf", "letter-mim"],
  }),
  atom({
    id: "grammar-hadha-hadhihi",
    kind: "GRAMMAR",
    canonicalArabic: "هذا / هذه",
    vocalizedArabic: "هٰذَا / هٰذِهِ",
    englishGloss: "this (m. / f.)",
    prerequisiteIds: ["letter-ha", "letter-dhal"],
  }),
  atom({
    id: "grammar-dhalika-tilka",
    kind: "GRAMMAR",
    canonicalArabic: "ذلك / تلك",
    vocalizedArabic: "ذٰلِكَ / تِلْكَ",
    englishGloss: "that (m. / f.)",
    prerequisiteIds: ["letter-dhal", "letter-lam", "letter-kaf"],
  }),
  atom({
    id: "grammar-nisba",
    kind: "GRAMMAR",
    canonicalArabic: "ـيّ / ـيّة",
    vocalizedArabic: "عَرَبِيّ / عَرَبِيَّة",
    englishGloss: "nisba adjective ending (nationality/relation)",
    prerequisiteIds: ["word-arabiyya", "letter-ya"],
  }),
];
