import type { KnowledgeAtom } from "@/domain/learning/types";
import { atom } from "./atom";

/** Multiword constructions and ready-to-use MSA phrases. */
export const PHRASE_ATOMS: KnowledgeAtom[] = [
  atom({
    id: "phrase-my-name",
    kind: "CONSTRUCTION",
    canonicalArabic: "اسمي",
    vocalizedArabic: "اِسْمِي",
    englishGloss: "my name is…",
    prerequisiteIds: ["word-ismi"],
  }),
  atom({
    id: "phrase-what-is-your-name",
    kind: "CONSTRUCTION",
    canonicalArabic: "ما اسمك",
    vocalizedArabic: "مَا اسْمُكَ؟",
    englishGloss: "What is your name?",
    prerequisiteIds: ["grammar-ma-what", "word-ism"],
  }),
  atom({
    id: "phrase-learn-arabic",
    kind: "CONSTRUCTION",
    canonicalArabic: "أنا أتعلم العربية",
    vocalizedArabic: "أَنَا أَتَعَلَّمُ العَرَبِيَّةَ",
    englishGloss: "I am learning Arabic",
    prerequisiteIds: ["pronoun-ana", "verb-ataallam", "word-arabiyya"],
  }),
  atom({
    id: "phrase-i-write-book",
    kind: "CONSTRUCTION",
    canonicalArabic: "أكتب كتابا",
    vocalizedArabic: "أَكْتُبُ كِتَابًا",
    englishGloss: "I write a book",
    prerequisiteIds: ["verb-aktub", "word-kitab"],
  }),
  atom({
    id: "phrase-i-read-book",
    kind: "CONSTRUCTION",
    canonicalArabic: "أقرأ كتابا",
    vocalizedArabic: "أَقْرَأُ كِتَابًا",
    englishGloss: "I read a book",
    prerequisiteIds: ["verb-aqra", "word-kitab"],
  }),
  atom({
    id: "phrase-in-house",
    kind: "CONSTRUCTION",
    canonicalArabic: "في البيت",
    vocalizedArabic: "فِي البَيْتِ",
    englishGloss: "in the house",
    prerequisiteIds: ["particle-fi", "word-bayt", "grammar-al"],
  }),
  atom({
    id: "phrase-in-school",
    kind: "CONSTRUCTION",
    canonicalArabic: "في المدرسة",
    vocalizedArabic: "فِي المَدْرَسَةِ",
    englishGloss: "at school",
    prerequisiteIds: ["particle-fi", "word-madrasa", "grammar-al"],
  }),
  atom({
    id: "phrase-in-library",
    kind: "CONSTRUCTION",
    canonicalArabic: "في المكتبة",
    vocalizedArabic: "فِي المَكْتَبَةِ",
    englishGloss: "in the library",
    prerequisiteIds: ["particle-fi", "word-maktaba"],
  }),
  atom({
    id: "phrase-from-city",
    kind: "CONSTRUCTION",
    canonicalArabic: "من المدينة",
    vocalizedArabic: "مِنَ المَدِينَةِ",
    englishGloss: "from the city",
    prerequisiteIds: ["particle-min", "word-madina"],
  }),
  atom({
    id: "phrase-to-market",
    kind: "CONSTRUCTION",
    canonicalArabic: "إلى السوق",
    vocalizedArabic: "إِلَى السُّوقِ",
    englishGloss: "to the market",
    prerequisiteIds: ["particle-ila", "word-suq"],
  }),
  atom({
    id: "phrase-with-friend",
    kind: "CONSTRUCTION",
    canonicalArabic: "مع صديق",
    vocalizedArabic: "مَعَ صَدِيقٍ",
    englishGloss: "with a friend",
    prerequisiteIds: ["particle-ma3a", "word-sadiq"],
  }),
  atom({
    id: "phrase-i-want-coffee",
    kind: "CONSTRUCTION",
    canonicalArabic: "أريد قهوة",
    vocalizedArabic: "أُرِيدُ قَهْوَةً",
    englishGloss: "I want coffee",
    prerequisiteIds: ["verb-uriid", "word-qahwa"],
  }),
  atom({
    id: "phrase-i-drink-water",
    kind: "CONSTRUCTION",
    canonicalArabic: "أشرب ماء",
    vocalizedArabic: "أَشْرَبُ مَاءً",
    englishGloss: "I drink water",
    prerequisiteIds: ["verb-ashrab", "word-maa"],
  }),
  atom({
    id: "phrase-i-eat-bread",
    kind: "CONSTRUCTION",
    canonicalArabic: "آكل خبزا",
    vocalizedArabic: "آكُلُ خُبْزًا",
    englishGloss: "I eat bread",
    prerequisiteIds: ["verb-akul", "word-khubz"],
  }),
  atom({
    id: "phrase-i-go-to-school",
    kind: "CONSTRUCTION",
    canonicalArabic: "أذهب إلى المدرسة",
    vocalizedArabic: "أَذْهَبُ إِلَى المَدْرَسَةِ",
    englishGloss: "I go to school",
    prerequisiteIds: ["verb-adhhab", "particle-ila", "word-madrasa"],
  }),
  atom({
    id: "phrase-i-live-in",
    kind: "CONSTRUCTION",
    canonicalArabic: "أسكن في",
    vocalizedArabic: "أَسْكُنُ فِي…",
    englishGloss: "I live in…",
    prerequisiteIds: ["verb-askun", "particle-fi"],
  }),
  atom({
    id: "phrase-i-work-in",
    kind: "CONSTRUCTION",
    canonicalArabic: "أعمل في",
    vocalizedArabic: "أَعْمَلُ فِي…",
    englishGloss: "I work in…",
    prerequisiteIds: ["verb-a3mal", "particle-fi"],
  }),
  atom({
    id: "phrase-i-dont-understand",
    kind: "CONSTRUCTION",
    canonicalArabic: "لا أفهم",
    vocalizedArabic: "لَا أَفْهَمُ",
    englishGloss: "I do not understand",
    prerequisiteIds: ["grammar-la-negation", "verb-afham"],
  }),
  atom({
    id: "phrase-i-speak-arabic",
    kind: "CONSTRUCTION",
    canonicalArabic: "أتكلم العربية",
    vocalizedArabic: "أَتَكَلَّمُ العَرَبِيَّةَ",
    englishGloss: "I speak Arabic",
    prerequisiteIds: ["verb-atakallam", "word-arabiyya"],
  }),
  atom({
    id: "phrase-good-morning",
    kind: "CONSTRUCTION",
    canonicalArabic: "صباح الخير",
    vocalizedArabic: "صَبَاحُ الخَيْرِ",
    englishGloss: "good morning",
    prerequisiteIds: ["word-sabah", "letter-kha"],
  }),
  atom({
    id: "phrase-good-evening",
    kind: "CONSTRUCTION",
    canonicalArabic: "مساء الخير",
    vocalizedArabic: "مَسَاءُ الخَيْرِ",
    englishGloss: "good evening",
    prerequisiteIds: ["word-masa"],
  }),
  atom({
    id: "phrase-how-are-you-m",
    kind: "CONSTRUCTION",
    canonicalArabic: "كيف حالك",
    vocalizedArabic: "كَيْفَ حَالُكَ؟",
    englishGloss: "How are you? (to a man)",
    prerequisiteIds: ["letter-kaf", "letter-ya", "letter-fa", "letter-haa"],
  }),
  atom({
    id: "phrase-i-am-fine",
    kind: "CONSTRUCTION",
    canonicalArabic: "أنا بخير",
    vocalizedArabic: "أَنَا بِخَيْرٍ",
    englishGloss: "I am fine",
    prerequisiteIds: ["pronoun-ana", "particle-bi"],
  }),
  atom({
    id: "phrase-where-is-the-house",
    kind: "CONSTRUCTION",
    canonicalArabic: "أين البيت",
    vocalizedArabic: "أَيْنَ البَيْتُ؟",
    englishGloss: "Where is the house?",
    prerequisiteIds: ["grammar-ayna-where", "word-bayt"],
  }),
  atom({
    id: "phrase-this-is-a-book",
    kind: "CONSTRUCTION",
    canonicalArabic: "هذا كتاب",
    vocalizedArabic: "هٰذَا كِتَابٌ",
    englishGloss: "This is a book",
    prerequisiteIds: ["grammar-hadha-hadhihi", "word-kitab"],
  }),
  atom({
    id: "phrase-that-is-a-school",
    kind: "CONSTRUCTION",
    canonicalArabic: "تلك مدرسة",
    vocalizedArabic: "تِلْكَ مَدْرَسَةٌ",
    englishGloss: "That is a school",
    prerequisiteIds: ["grammar-dhalika-tilka", "word-madrasa"],
  }),
  atom({
    id: "phrase-the-book-is-new",
    kind: "CONSTRUCTION",
    canonicalArabic: "الكتاب جديد",
    vocalizedArabic: "الكِتَابُ جَدِيدٌ",
    englishGloss: "The book is new",
    prerequisiteIds: ["word-kitab", "word-jadid", "grammar-al"],
  }),
  atom({
    id: "phrase-the-house-is-big",
    kind: "CONSTRUCTION",
    canonicalArabic: "البيت كبير",
    vocalizedArabic: "البَيْتُ كَبِيرٌ",
    englishGloss: "The house is big",
    prerequisiteIds: ["word-bayt", "word-kabir"],
  }),
  atom({
    id: "phrase-i-like-coffee",
    kind: "CONSTRUCTION",
    canonicalArabic: "أحب القهوة",
    vocalizedArabic: "أُحِبُّ القَهْوَةَ",
    englishGloss: "I like coffee",
    prerequisiteIds: ["verb-uhibb", "word-qahwa"],
  }),
  atom({
    id: "phrase-today-i-study",
    kind: "CONSTRUCTION",
    canonicalArabic: "اليوم أتعلم",
    vocalizedArabic: "اليَوْمَ أَتَعَلَّمُ",
    englishGloss: "Today I learn / study",
    prerequisiteIds: ["word-al-yawm", "verb-ataallam"],
  }),
  atom({
    id: "phrase-tomorrow-i-go",
    kind: "CONSTRUCTION",
    canonicalArabic: "غدا أذهب",
    vocalizedArabic: "غَدًا أَذْهَبُ",
    englishGloss: "Tomorrow I go",
    prerequisiteIds: ["word-ghadan", "verb-adhhab"],
  }),
  atom({
    id: "phrase-student-of-arabic",
    kind: "CONSTRUCTION",
    canonicalArabic: "طالب العربية",
    vocalizedArabic: "طَالِبُ العَرَبِيَّةِ",
    englishGloss: "student of Arabic",
    prerequisiteIds: ["grammar-idafa-intro", "word-talib", "word-arabiyya"],
  }),
  atom({
    id: "phrase-is-this-easy",
    kind: "CONSTRUCTION",
    canonicalArabic: "هل هذا سهل",
    vocalizedArabic: "هَلْ هٰذَا سَهْلٌ؟",
    englishGloss: "Is this easy?",
    prerequisiteIds: ["grammar-hal-question", "grammar-hadha-hadhihi", "word-sahl"],
  }),
  atom({
    id: "phrase-how-many-books",
    kind: "CONSTRUCTION",
    canonicalArabic: "كم كتابا",
    vocalizedArabic: "كَمْ كِتَابًا؟",
    englishGloss: "How many books?",
    prerequisiteIds: ["grammar-kam-how-many", "word-kitab"],
  }),
  atom({
    id: "phrase-please-and-thanks",
    kind: "CONSTRUCTION",
    canonicalArabic: "من فضلك وشكرا",
    vocalizedArabic: "مِنْ فَضْلِكَ، وَشُكْرًا",
    englishGloss: "please, and thank you",
    prerequisiteIds: ["word-min-fadlik", "word-shukran", "particle-wa"],
  }),
  atom({
    id: "phrase-i-want-to-learn",
    kind: "CONSTRUCTION",
    canonicalArabic: "أريد أن أتعلم",
    vocalizedArabic: "أُرِيدُ أَنْ أَتَعَلَّمَ",
    englishGloss: "I want to learn",
    prerequisiteIds: ["verb-uriid", "verb-ataallam"],
  }),
  atom({
    id: "phrase-arabic-is-beautiful",
    kind: "CONSTRUCTION",
    canonicalArabic: "العربية جميلة",
    vocalizedArabic: "العَرَبِيَّةُ جَمِيلَةٌ",
    englishGloss: "Arabic is beautiful",
    prerequisiteIds: ["word-arabiyya", "word-jamiil"],
  }),
  atom({
    id: "phrase-the-lesson-is-important",
    kind: "CONSTRUCTION",
    canonicalArabic: "الدرس مهم",
    vocalizedArabic: "الدَّرْسُ مُهِمٌّ",
    englishGloss: "The lesson is important",
    prerequisiteIds: ["word-dars", "word-muhimm"],
  }),
  atom({
    id: "phrase-on-the-table",
    kind: "CONSTRUCTION",
    canonicalArabic: "على المكتب",
    vocalizedArabic: "عَلَى المَكْتَبِ",
    englishGloss: "on the desk",
    prerequisiteIds: ["particle-3ala", "word-maktab"],
  }),
  atom({
    id: "phrase-with-the-family",
    kind: "CONSTRUCTION",
    canonicalArabic: "مع الأسرة",
    vocalizedArabic: "مَعَ الأُسْرَةِ",
    englishGloss: "with the family",
    prerequisiteIds: ["particle-ma3a", "word-usra"],
  }),
  atom({
    id: "phrase-i-hear-and-speak",
    kind: "CONSTRUCTION",
    canonicalArabic: "أسمع وأتكلم",
    vocalizedArabic: "أَسْمَعُ وَأَتَكَلَّمُ",
    englishGloss: "I hear and I speak",
    prerequisiteIds: ["verb-asma3", "verb-atakallam", "particle-wa"],
  }),
  atom({
    id: "phrase-one-book-two-pens",
    kind: "CONSTRUCTION",
    canonicalArabic: "كتاب واحد وقلمان",
    vocalizedArabic: "كِتَابٌ وَاحِدٌ وَقَلَمَانِ",
    englishGloss: "one book and two pens (intro dual idea)",
    prerequisiteIds: ["word-kitab", "word-wahid", "word-qalam", "particle-wa"],
  }),
  atom({
    id: "phrase-good-night",
    kind: "CONSTRUCTION",
    canonicalArabic: "تصبح على خير",
    vocalizedArabic: "تُصْبِحُ عَلَى خَيْرٍ",
    englishGloss: "good night (lit. wake up well)",
    prerequisiteIds: ["particle-3ala", "letter-kha"],
  }),
  atom({
    id: "phrase-welcome-to-nawa",
    kind: "CONSTRUCTION",
    canonicalArabic: "أهلا بك في نوى",
    vocalizedArabic: "أَهْلًا بِكَ فِي نَوَى",
    englishGloss: "welcome to Nawa",
    prerequisiteIds: ["word-ahlan", "particle-bi", "particle-fi"],
  }),
];
